---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	router(router)
	org_assistant(org_assistant)
	owasp_assistant(owasp_assistant)
	tools(tools)
	__end__([<p>__end__</p>]):::last
	__start__ --> router;
	org_assistant -.-> __end__;
	org_assistant -.-> tools;
	router -.-> __end__;
	router -.-> org_assistant;
	router -.-> owasp_assistant;
	tools --> org_assistant;
	owasp_assistant --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
